// Inlines the Font Awesome Free (solid) icons the teacher screens use into web/fa.js, so they work offline.
// Run: node tools/make-fa.mjs
import { writeFileSync } from 'node:fs';
const V = '6.5.2';
const NAMES = ['table-cells-large', 'users', 'comment-dots', 'bullhorn', 'plus', 'download', 'table', 'bell', 'bell-slash',
  'magnifying-glass', 'circle-check', 'circle-exclamation', 'clock-rotate-left', 'calendar-check', 'book-open', 'user',
  'thumbtack', 'print', 'expand', 'copy', 'rotate', 'xmark', 'trash-can', 'arrow-right', 'comments'];
const out = {};
for (const n of NAMES) {
  const svg = await (await fetch(`https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@${V}/svgs/solid/${n}.svg`)).text();
  const vb = /viewBox="([^"]+)"/.exec(svg)[1];
  const d = /<path d="([^"]+)"/.exec(svg)[1];
  out[n] = [vb, d];
}
writeFileSync(new URL('../web/fa.js', import.meta.url), `// Font Awesome Free ${V} solid icons (CC BY 4.0, https://fontawesome.com/license/free). Generated by tools/make-fa.mjs.
const I = ${JSON.stringify(out)};
export const fa = (name, cls = '') => \`<svg class="fa \${cls}" viewBox="\${I[name][0]}" aria-hidden="true"><path d="\${I[name][1]}"/></svg>\`;
`);
console.log('ok', Object.keys(out).length);
